wad2/what_the_book/urls.py
from django.urls import path
from what_the_book import views

app_name = 'what_the_book'

urlpatterns = [
    path('', views.home, name='home'),
    path('contactus/', views.contactus, name='contactus'),
    path('request_book/', views.request_book, name='request_book'),
    path('book/<slug:book_name_slug>/', views.show_book, name='show_book'),
    path('book/<slug:book_name_slug>/make_review/',
         views.make_review, name='make_review'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('account/', views.account, name='account'),
    path('logout/', views.user_logout, name='logout'),

]

wad2/what_the_book_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from what_the_book import views

urlpatterns = [
    path('', views.redirect_to_home),
    path('home/', include('what_the_book.urls')),
    path('what_the_book/', include('what_the_book.urls')),
    path('admin/', admin.site.urls),
    path('book/<slug:book_name_slug>/', views.show_book, name='show_book'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wad2/what_the_book/models.py
from django.db import models
from django.template.defaultfilters import slugify
from datetime import datetime


class User(models.Model):
    userId = models.AutoField(unique=True, primary_key=True)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    profilePicture = models.ImageField(blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.username)
        super(User, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'users'

    def __str__(self):
        return f"{self.username}"


class Admin(models.Model):
    userId = models.AutoField(unique=True, primary_key=True)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    profilePicture = models.ImageField()

    def __str__(self):
        return f"{self.username}"


class Book(models.Model):
    addedBy = models.ForeignKey(
        Admin, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=30)
    author = models.CharField(max_length=20)
    coverPicture = models.ImageField(
        upload_to='images/book_covers/', blank=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Book, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'books'

    def __str__(self):
        return f"{self.title} by {self.author}"


class BookToRequest(models.Model):
    requestedBy = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    readBy = models.ForeignKey(
        Admin, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=30)
    author = models.CharField(max_length=20)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BookToRequest, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'requested books'

    def __str__(self):
        return f"{self.title} requested by {self.requestedBy}"


class Review(models.Model):
    reviewOf = models.ForeignKey(
        Book, on_delete=models.CASCADE, null=True, blank=True)
    createdBy = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=30)
    mainText = models.TextField()
    createdOn = models.DateField()
    likes = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.likes is not None:
            if self.likes < 0:
                self.likes = 0
        if self.createdOn is not None:
            if self.createdOn > datetime.now().date():
                self.createdOn = datetime.now().date()
        self.slug = slugify(self.title)
        super(Review, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'reviews'

    def __str__(self):
        return f"Review of {self.reviewOf}  by {self.createdBy}"

wad2/what_the_book/forms.py
from django import forms
from what_the_book.models import BookToRequest, Review
from what_the_book.models import User as UserPicture
from django.contrib.auth.models import User


class BookRequestForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the Book you would like to add")
    author = forms.CharField(max_length=128,
                             help_text="Please enter the author of the Book you would like to add")

    class Meta:
        model = BookToRequest
        fields = ('title', 'author')


class ReviewForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter title for review")
    mainText = forms.CharField(max_length=4000,
                               help_text="Please write your review")

    class Meta:
        model = Review
        fields = ('title', 'mainText')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password',)


class UserPictureForm(forms.ModelForm):
    class Meta:
        model = UserPicture
        fields = ('profilePicture',)

wad2/what_the_book/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from what_the_book.models import Book, Review, User, Admin
from what_the_book.forms import BookRequestForm, ReviewForm, UserForm, UserPictureForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone


def redirect_to_home(request):
    return redirect(reverse('what_the_book:home'))


def home(request):
    book_list = Book.objects.order_by('title')
    context_dict = {}
    context_dict['books'] = book_list
    return render(request, 'what_the_book/home.html', context=context_dict)


def contactus(request):
    return render(request, 'what_the_book/contactus.html', context={})


def show_book(request, book_name_slug):
    context_dict = {}
    try:
        book = Book.objects.get(
            Q(title__iexact=book_name_slug.replace('-', ' ')))
        reviews = Review.objects.filter(reviewOf=book)
    except Book.DoesNotExist:
        book = None
        reviews = Review.objects.none()

    context_dict['book'] = book
    context_dict['reviews'] = reviews
    return render(request, 'what_the_book/book.html', context_dict)


def request_book(request):
    form = BookRequestForm()

    if request.method == 'POST':
        form = BookRequestForm()
        if form.is_valid():
            form.save(commit=True)

            return redirect('/home/')
        else:
            print(form.errors)

    return render(request, 'what_the_book/request_book.html', {'form': form})


@login_required
def make_review(request, book_name_slug):

    if request.user.is_authenticated:
        username = request.user.username
    try:
        user = User.objects.get(username=username)
        reviewOf = Book.objects.get(slug=book_name_slug)

    except Book.DoesNotExist:
        reviewOf = None

    if reviewOf is None:
        return redirect('what_the_book')

    form = ReviewForm()

    if request.method == 'POST':
        form = ReviewForm(request.POST)

        if form.is_valid():
            review = form.save()
            review.reviewOf = reviewOf
            review.createdBy = user

            review.likes = 0
            review.createdOn = timezone.now()
            review.save()

            return redirect(reverse('what_the_book:show_book', kwargs={'book_name_slug': book_name_slug
                                                                       }))
        else:
            print(form.errors)

    context_dict = {'form': form, 'reviewOf': reviewOf,
                    'book_name_slug': book_name_slug}

    return render(request, 'what_the_book/make_review.html', context=context_dict)


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        user_picture_form = UserPictureForm(request.POST)

        if user_form.is_valid() and user_picture_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            picture_user = user_picture_form.save(commit=False)
            picture_user.username = user_form['username'].data
            picture_user.password = user_form['password'].data

            if 'profilePicture' in request.FILES:
                picture_user.profilePicture = request.FILES['profilePicture']

            picture_user.save()
            registered = True
        else:
            print(user_form.errors, user_picture_form.errors)
    else:
        user_form = UserForm()
        user_picture_form = UserPictureForm()

    return render(request, 'what_the_book/register.html', context={'user_form': user_form,
                                                                   'user_picture_form': user_picture_form,
                                                                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect_to_home(request)
            else:
                return HttpResponse("Your account is disabled.")
        else:
            return HttpResponse("Invalid login details.")
    else:
        return render(request, 'what_the_book/login.html')


@login_required
def account(request):
    if request.user.is_authenticated:
        username = request.user.username
    try:
        user = User.objects.get(username=username)
        reviews = Review.objects.filter(createdBy=user)
    except User.DoesNotExist:
        user = None
        reviews = None
    except Review.DoesNotExist:
        reviews = None

    context_dict = {'user': user, 'reviews': reviews}
    return render(request, 'what_the_book/account.html', context=context_dict)


@login_required
def user_logout(request):
    logout(request)
    return redirect_to_home(request)

wad2/templates/what_the_book/account.html
{% extends 'what_the_book/base.html' %}
{% load static %}

Username: {{ user.username }}
{% if user.profilePicture %}
Profile Picture: <img src="{{ user.profilePicture.url }}"/>
{% endif %}

{% for review in reviews %}
<div class = "reviews">
    <h3>{{ review.title }}</h3>
    <p>By {{ review.createdBy }}</p>
    <p>{{ review.mainText }}</p>
    <p>Likes: {{ review.likes }}</p>
</div>
{% empty %}
<p>No reviews yet.</p>
{% endfor %}

wad2/templates/what_the_book/base.html
<!DOCTYPE html>
{% load staticfiles %}



<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title_block %}
      What The Book?
      {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'main_stylesheet.css' %}" />

</head>

<body>
   <header> <img src = "{% static 'bookLogoNoBg.png' %}"
                  alt = "hallo" width = "60" height ="60" class = "logoPlacement">
        <h1>What The Book</h1> <!-- will be styled by header in css file -->
    </header>

   <div  class = "navBar"><!-- need to link to horizontal navbar class -->
    <ul>
      <li><a href ="{% url 'what_the_book:home' %}">Home</a></li>
      {% if user.is_authenticated %}
      <li><a href ="{% url 'what_the_book:request_book' %}">Request A new book</a></li>
      <li><a href ="{% url 'what_the_book:account' %}">View account</a></li>
      <li><a href ="{% url 'what_the_book:logout' %}">Logout</a></li>
      {% else %}
      <li><a href ="{% url 'what_the_book:register' %}">Register for an account</a></li>
      <li><a href ="{% url 'what_the_book:login' %}">Login</a></li>
      {% endif %}
      <li><a href ="{% url 'what_the_book:contactus' %}">Contact Us</a></li>
    </ul>

</div>
<div>
  {% block body_block %}
  {% endblock %}
</div>

<br />




</body>
</html>

wad2/templates/what_the_book/book.html
{% extends 'what_the_book/base.html' %}

<!-- DONE -->

<html>
    {% block title_block %}
            {% if book %}
            {{ book.title }}
            {% else %}
            Book
            {% endif %}
    {% endblock %}

    {% block body_block %}
        <div class = "book-review">
            <div class = "reviewLeft">
            {% if book %}
            <h1>{{ book.title }}</h1>
            <p>Author: {{ book.author }}</p>
            {% if book.coverPicture %}
                <img src="{{ book.coverPicture.url }}" alt="{{ book.title }} cover picture" width = "150" height = "180">
            {% else %}
                <p>No cover picture available.</p>
            {% endif %}
        </div>

        <div class="reviewRight">
            <h2>Reviews:</h2>
            {% for review in reviews %}
                <div class = "reviews">
                    <h3>{{ review.title }}</h3>
                    <p>By {{ review.createdBy }}</p>
                    <p>{{ review.mainText }}</p>
                    <strong>Likes: {{ review.likes }}</strong>

                </div>
            {% empty %}
                <p>No reviews yet.</p>
            {% endfor %}
        </div>
        {% else %}
            <p>Book not found.</p>
        {% endif %}
                {% if user.is_authenticated %}
                <a href="{% url 'what_the_book:make_review' book.slug %}"> Review Book</a><br />
                {% endif %}
        
        </div>

    {% endblock %}

wad2/templates/what_the_book/contactus.html
{% extends 'what_the_book/base.html' %}
{% load static %}

<!-- just need to connect css -->

{% block title_block %}
Contact us
{% endblock %}

<div id = "navBar">
    <!-- <img src="{{ MEDIA_URL }}macbeth.jpg" alt="Macbeth book cover."/> -->
    <a href="/home/" class = "navElements"> Home</a><br />
</div>


    {% block body_block %}
        <div class = "contactInfo">
            <h1> CONTACT US</h1>
            If you are requesting a new book for the site, please include the title and
            author's name.<br />
            <br />
            If you are reporting an account, please include the username and the reason for reporting them.<br />
            <br />
            Information about how long it may take to reply to enquiries/new books to be uploaded<br />
        </div>

        <div class = "formPlacement">
            <form>
                <label>Username</label><br />
                <input type = "text" size = 20><br />
                <br />

                <label>Please enter your message below</label><br />
                <input type = "text" size = 50 cols = 20><br />
                <br />

                <input type = "submit" value = "Submit">
            </form>
        </div>




    {% endblock %}

wad2/templates/what_the_book/home.html
{% extends 'what_the_book/base.html' %}

{% load staticfiles %}
<!-- DONE -->
        
        <link rel = "stylesheet" href = "{% static 'main_stylesheet.css' %}">

        <div> <!-- add in horizontal navbar calls -->
            <a href="/home/contactus/"> Contact us</a><br />
            <a href="/what_the_book/request_book/"> Request a new book</a><br />
        </div>
    {% block body_block %}

                <div class = "verticalNav">
        {% if books %}
            <ul>
                <label>Available Books:</label>
                {% for book in books %}
                <li><a href="{% url 'show_book' book.title|slugify %}">{{ book.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p> No books found. </p>
        {% endif %}
        </div>

        <div class="filler"></div>

        <div class = "rightSectionImg">
            <h1> Welcome! </h1>
                    <img src = "{% static 'libPhoto.jfif' %}"
                         alt = "Library Photo" width = "600" height = "400" ><br/>
            <br />

            <p>

                <!-- will be properly organised by the css once fixed -->
                Welcome to What The Book, the site where you can talk about your
                favourite (or least favourite) books with hundreds of other
                enthusiasts! <br /><strong>We hope you enjoy your visit!</strong></p>
        </div>





        <br />
        <br />


{% endblock %}

wad2/templates/what_the_book/login.html
{% extends 'what_the_book/base.html' %}
{% load staticfiles %}

<!-- connect css sheet -->

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to What the Book</h1>
    <form id="login_form" method="post" action="{% url 'what_the_book:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" style = "margin: 10px"/>
        <br>
        Password: <input type="password" name="password" value="" size="50" style = "margin: 10px"/>
        <br>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

wad2/templates/what_the_book/make_review.html
{% extends 'what_the_book/base.html' %}

{% load static %}


        {% block title_block %}
            What the Book?
        {% endblock %}


{% block body_block %}
        <h1>Make review of {{ reviewOf.title }}</h1>

        <div>
            <form id="review_form" method="post" action="{% url 'what_the_book:show_book' book_name_slug %}">
                {% csrf_token %}

                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}<br /><br />
                {% endfor %}
                <input type="submit" name="submit" value="Review Book" />
            </form>
        </div>


{% endblock %}

wad2/templates/what_the_book/register.html
{% extends 'what_the_book/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock title_block %}
<!-- nothing to change, just need css sheet to work -->

{% block body_block %}
    <h1> Register for What the Book! </h1>

    {% if registered %}
        Registration successful! <br>
        <a href = "{% url 'what_the_book:home' %}">Return to Homepage.</a><br>

    {% else %}
        Registration form:
        <form id="user_form" method="post" action="{% url 'what_the_book:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{user_form.as_p}}
            {{user_picture_form.as_p}}
            <input type="submit" name="submit" value="Register">
        </form>

    {% endif %}
{% endblock body_block %}

wad2/templates/what_the_book/request_book.html
{% extends 'what_the_book/base.html' %}

{% load static %}

<!-- connect css -->

{% block title_block %}
            What the Book?
{% endblock %}

{% block body_block %}
        <h1>Request a book to be added</h1>
        
        <div>
            <form id="book_request_form" method="post" action="/home/request_book/">
                
                {% csrf_token %}
                
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}<br /><br />
                {% endfor %}
                <input type="submit" name="submit" value="Create Book Request" />
            </form>
        </div>


{% endblock %}